### ISSUE TITLE
Accidental controller publishing 

### ISSUE THREAD

**Issue by Windvis** [sinankeskin/ember-inputmask#298]
It seems that a controller used in the dummy app [was accidentally created in the addon folder](https://github.com/sinankeskin/ember-inputmask/blob/main/addon/controllers/application.js) which means it will be pulled into consuming apps as well.

**Comment by sinankeskin** [comment]
Woops. Thanks for the warning. I'll remove and create a version ASAP. Sorry about that @Windvis

**Comment by sinankeskin** [comment]
Removed. Thanks a lot.
