### ISSUE TITLE
modifier version

### ISSUE THREAD

**Issue by Windvis** [sinankeskin/ember-inputmask#299]
It would be nice if the input mask functionality was available as a custom modifier as well. That way it could be applied to any input element you want. It would also replace the need for ember-render-modifiers addon since the component could probably use that modifier internally.

**Comment by sinankeskin** [comment]
Perfectly make sense @Windvis Thank you for the suggestion. I'll add.

**Comment by sinankeskin** [comment]
Hey @Windvis try [v3.0.0](https://www.npmjs.com/package/ember-inputmask5) please. Thanks a lot.
