### ISSUE TITLE
V2 Format

### ISSUE THREAD

**Issue by cah-briangantzler** [sinankeskin/ember-inputmask#348]
Having difficulty with an old ember addon shimming inputmask I was using and just going to write my own, luckily stumbled across this which seems to be pretty close to what I would have done.

Would you be open to a PR that converts this to a V2 addon?

Also would like to do get some tests in to help with the ember observer score :)

**Comment by sinankeskin** [comment]
Sure @cah-briangantzler you are always welcome. Please be my guest.

**Comment by cah-briangantzler** [comment]
Im more use to `yarn` this looks like you prefer `npm` will try to do it that way, most my guides and examples use `yarn` though.

**Comment by sinankeskin** [comment]
I'm totally down.

**Comment by cah-briangantzler** [comment]
While updating to V2, the ember-modifier is being updated to 3.2 (previously on 3.1 I would assume). This means there are some deprecations showing in the console. I intend to fix them, not sure if it will be a breaking change or not. You should also read https://github.com/ember-modifier/ember-modifier/blob/v3.2.7/MIGRATIONS.md so you understand what/why the changes are happening

**Comment by sinankeskin** [comment]
Yes I know. I've read that. new `modify` hook to rule them all 😄 but for this addon it shouldn't be a big problem.

**Comment by cah-briangantzler** [comment]
Yes, should be an easy fix. Just letting you know was going to roll that in as well

**Comment by cah-briangantzler** [comment]
How tied are you to the lazy import of inputmask at https://github.com/sinankeskin/ember-inputmask/blob/main/addon/modifiers/inputmask.js#L17.

Trying to write a couple tests and it sometimes fails. I dont think the `settled` of ember knows about the promise and sometimes the test asserts run before the inputmask is attached to the element

**Comment by sinankeskin** [comment]
Lazy import was a request by a user. This is kind of good if we have feature. I don't know can modify hook be async.

didUpdateArguments and related things all my mistakes. I don't think needed and can be removed.

getArgs things are intentional. We could use both as a component and as a modifier. If we want to use as a component args comes as first positional parameter to modifier and because of that I believe we should not remove this behaviour @cah-briangantzler

**Comment by cah-briangantzler** [comment]
Ahh, I should have caught that on the args. 

Will look and see if modify is async and ask about getting it so if it is not. Else I will have to put a wait in the tests which Im sure is a smell. When users write tests that use this, Im would assume they would run into the same issue

**Comment by cah-briangantzler** [comment]
Just to clarify a something, this means you do NOT support updating any of the args after the input field is initially created. Is that correct?  I say this because of the error in didUpdateArguments and the fact that _setInputMask creates a NEW instance if it were to update. Creating a new instance means that if the user was using registerAPI, they now have access to an old instance.  Might have been better to have sent your own API in registerAPI instead of the mask.

Do I read this correctly? and What is the course of action you would like to take?

**Comment by sinankeskin** [comment]
> Just to clarify a something, this means you do NOT support updating any of the args after the input field is initially created. Is that correct? I say this because of the error in didUpdateArguments and the fact that _setInputMask creates a NEW instance if it were to update. Creating a new instance means that if the user was using registerAPI, they now have access to an old instance. Might have been better to have sent your own API in registerAPI instead of the mask.
> 
> If I would have multiple input fields on the screen, doesnt this set the default over and over again? The lazy import is getting in the way of making that any better as well.
> 
> Do I read this correctly? and What is the course of action you would like to take?

You are right, my initial thought was "User should not update any args after the initialization" but second thought, this could be necessary. So, we need to make sure  to invoke `_setInputMask` with the new args. I believe InputMask will destroy the old instance and adds a new one to element. I'm not totally sure though.

**Comment by cah-briangantzler** [comment]
ember-auto-import analyzes the import for tree shaking, but pretty sure thats the browser one. Both the static and dynamic he talks about here https://github.com/ef4/ember-auto-import#dynamic-import as the browser ones.

Whats the direction on registerAPI? if a new instance is created the registerAPI has to be called again, which means it needs to move out of initialize which is a problem for the first time use. The register will be called with a null inputmask if the dynamic import is not completed. Code could get messy. Your call? Keep the dynamic import and try to deal with it, or make it static?


Keeping the dynamic import is going to cause some complexity with not setting the defaults over and over

**Comment by sinankeskin** [comment]
> ember-auto-import analyzes the import for tree shaking, but pretty sure thats the browser one. Both the static and dynamic he talks about here https://github.com/ef4/ember-auto-import#dynamic-import as the browser ones.
> 
> Whats the direction on registerAPI? if a new instance is created the registerAPI has to be called again, which means it needs to move out of initialize which is a problem for the first time use. The register will be called with a null inputmask if the dynamic import is not completed. Code could get messy. Your call? Keep the dynamic import and try to deal with it, or make it static?
> 
> Keeping the dynamic import is going to cause some complexity with not setting the defaults over and over

I agree. Let's get rid of the dynamic import for now. But to overcome the `registerAPI` issue instead of returning inputmask instance let's return element itself that way if element binds to another instance we could get new inputmask instance without to much effort. What do you think? @cah-briangantzler

**Comment by cah-briangantzler** [comment]
I agree with that, but instead of returning the element, actually returning an API (that way we are not giving them acces to the element). Something like (not actual implementation, just an example)

```
    this.args.registerAPI.?({
         get inputmask = () => {
            return this.element.inputmask;
         } 
    });
```

This way you are returning an API with the property inputmask that dynamically looks it up. You would then be able to easily add more API if the need arises

This would be another breaking change as you are changing the signature of registerAPI

**Comment by sinankeskin** [comment]
Even better. 👍🏻

**Comment by cah-briangantzler** [comment]
I thought I could find a way around it, but appears that the only way to get the defaults to set once is an applicationInitializer.  I really try to avoid them but thats what is for, initializing the application

**Comment by sinankeskin** [comment]
Thank you again for the great upgrade 🙏
