### ISSUE TITLE
Add documentation + tests

### ISSUE THREAD

**Issue by aceol** [sinankeskin/ember-inputmask#548]
Hi Sinan, thanks for the project, 
We migrated from `ember-inputmask` to `ember-inputmask5` it's working good but we had some trouble in order to use it. 
We were considering adding a PR to add some docs + tests. 
Is that ok? Do you have any specific doc/test in mind?

**Comment by sinankeskin** [comment]
Done 🤝

**Comment by aceol** [comment]
We added 2 PR, hope it'll help

**Comment by aceol** [comment]
Glad to help, thanks for your contributions to the ember ecosystem!
